const iconNames: { [key: string]: string } = {
  'search-cancel': 'Clear Search Results',
  'video-record': 'Record Video',
  'cloudy-weather': 'Cloudy',
  'day-night-weather': 'Day Night',
  'fog-weather': 'Fog',
  'haze-weather': 'Haze',
  'lightning-bolt-weather': 'Lightning Bolt',
  'lightning-weather': 'Lightning',
  'light-snowy-weather': 'Light Snowy',
  'night-weather': 'Night',
  'rain-cloud-weather': 'Rain Cloud',
  'rain-cloud-weather-2': 'Rain Cloud 2',
  'snow-storm-weather': 'Snow Storm',
  'sunrise-weather': 'Sunrise',
  'sunset-weather': 'Sunset',
  'sun-weather': 'Sun',
  'temperature-weather': 'Temperature',
  'torrential-rain-weather': 'Torrential Rain',
  'windy-cloud-weather': 'Windy Cloud',
  'circles-menu-1': 'Dots Loading 1',
  'circles-menu-2': 'Dots Loading 2',
  'circles-menu-3': 'Dots Loading 3',
  'circles-menu-4': 'Dots Loading 4',
  'circles-menu-5': 'Dots Loading 5',
  'circles-menu-6': 'Dots Loading 6',
  'circle-square-1': 'Square 1',
  'circle-square-2': 'Square 2',
  'circle-square-triangle': 'Geometric Shapes',
  disappointed: 'Disappointed Face',
  embarrassed: 'Embarrassed Face',
  'in-love': 'In Love Face',
  laughing: 'Laughing Face',
  neutral: 'Neutral Face',
  sleeping: 'Sleeping Face',
  'facebook-like-morph': 'Facebook Like',
  'skip-forwards': 'Skip Forward',
  confused: 'Confused Face',
  'dribbble-circled-shake': 'Dribbble',
  'live-video-on': 'Live Video',
  'no-mobile-phones': 'No Mobile',
  'vk-circled-shake': 'VK',
  'cd-2': 'Compact Disk',
  receipt: 'Receipt Icon',
  'phonelink-ring': 'Phone Ring',
  portrait_mode_scanning: 'Portrait Mode Scanning',
  previous_location: 'Previous Location',
  'add-to-favorite': 'Add To Favorites',
  'cat-meow': 'Cat',
  'folder-with-files': 'Folder with File',
  'home-2': 'House',
  'kiss-panda': 'Panda Kiss',
  vomited: 'Vomiting',
};

export const iconCategories = [
  {
    name: 'UI',
    icons: [
      'alphabetical-sorting',
      'block-mic',
      'check',
      'checkmark-ok',
      'clear-filter',
      'delete',
      'expand',
      'expand-window',
      'download',
      'upload',
      'eye',
      'folder',
      'forward',
      'heart',
      'install',
      'left-right',
      'menu-arrow',
      'menu-close',
      'menu-minus',
      'numerical-sorting',
      'online',
      'quick',
      'settings',
      'refresh',
      'refresh-wait',
      'restart',
      'rotate',
      'search-cancel',
      'shield',
      'speech',
      'star',
      'stop',
      'switch',
      'thumb',
      'toggle',
      'trash',
      'unlock',
      'warning-1',
      'warning-2',
      'up-down',
      'fidget-spinner',
      'add',
      'warning-blink',
      'wifi-search',
      'activity',
      'alarm-clock',
      'bell',
      'book',
      'bookmark',
      'bookmark-in-book',
      'calendar',
      'calendar-tear',
      'check-circle',
      'design',
      'document',
      'double-tap',
      'drag-left',
      'drag-right',
      'edit',
      'edit-cancel',
      'edit-ok',
      'facebook-like-morph',
      'four-fingers',
      'fullscreen',
      'gift-heart',
      'globe',
      'hand-peace',
      'hand-scissors',
      'heart-in-hand',
      'icon-list-view',
      'menu-back',
      'menu-forward',
      'ok-hand',
      'one-finger',
      'paint-roller',
      'pencil',
      'play-load',
      'skip-backwards',
      'skip-forwards',
      'tap',
      'three-fingers',
      'trash-bin',
      'tune',
      'caps',
      'ok',
      'pin',
      'add-cloud',
      'add-folder',
      'attention-cloud',
      'favorite-cloud',
      'favorite-folder',
      'create-order',
      'delete-cloud',
      'delete-folder',
      'download-folder',
      'download-from-cloud',
      'face-id',
      'help-cloud',
      'load-from-cloud',
      'palm-scan',
      'refresh-cloud',
      'refresh-folder',
      'phonelink-ring',
      'photo-gallery',
      'portrait_mode_scanning',
      'qr-code',
      'previous_location',
      'synchronize-folder',
      'upload-to-cloud',
      'synchronize-cloud',
      'add-to-favorite',
      'add-to-collection',
      'bad-gateway',
      'come-back-later',
      'compass',
      'computer-display',
      'cursor',
      'delete-confirmation',
      'down-arrow',
      'fatal-error',
      'folder-with-files',
      'home',
      'home-2',
      'installing-updates',
      'list-is-empty',
      'login',
      'map',
      'map-marker',
      'map-pointer',
      'menu-open-and-close',
      'message-sent',
      'missed-call',
      'money',
      'no-connection',
      'no-messages',
      'open-archive',
      'order-completed',
      'page-under-construction',
      'phone-ringing',
      'place-marker',
      'print',
      'save-changes',
      'scroll-down-hand',
      'searching',
      'share',
      'sign-out',
      'submit-progress',
      'uninstalling-updates',
      'unsubscribed',
      'upgrade',
    ],
  },
  {
    name: 'Web',
    icons: [
      'wordpress-rotation',
      'broken-link',
      'cloud',
      'expand',
      'expand-window',
      'download',
      'upload',
      'open-letter',
      'subscribe-1',
      'subscribe-2',
      'subscribe-3',
      'mailbox',
      'warning-blink',
      'wifi-search',
      'book',
      'bookmark',
      'bookmark-in-book',
      'calendar',
      'calendar-tear',
      'check-circle',
      'design',
      'document',
      'edit',
      'edit-cancel',
      'edit-ok',
      'flag',
      'fullscreen',
      'globe',
      'heart-in-hand',
      'icon-list-view',
      'mug',
      'paint-roller',
      'pencil',
      'tea',
      'trash-bin',
      'tune',
      'book',
      'create-order',
      'help-cloud',
      'load-from-cloud',
      'medium',
      'refresh-cloud',
      'refresh-folder',
      'phonelink-ring',
      'photo-gallery',
      'previous_location',
      'add-to-favorite',
      'add-to-collection',
      'bad-gateway',
      'calendar-heart',
      'computer-display',
      'delivery',
      'down-arrow',
      'fatal-error',
      'folder-with-files',
      'guarantee',
      'home',
      'home-2',
      'internet',
      'map',
      'map-marker',
      'map-pointer',
      'medal-first-place',
      'medal-second-place',
      'medal-third-place',
      'menu-open-and-close',
      'message-sent',
      'movie',
      'no-comments',
      'no-messages',
      'page-under-construction',
      'prize',
      'unsubscribed',
    ],
  },
  {
    name: 'Social',
    icons: [
      'facebook',
      'facebook-circled-click',
      'facebook-circled-rotation',
      'facebook-circled-scale',
      'facebook-circled-shake',
      'facebook-messenger-click',
      'facebook-messenger-rotation',
      'facebook-messenger-scale',
      'facebook-messenger-shake',
      'linkedin-circled-click',
      'linkedin-circled-rotation',
      'linkedin-circled-scale',
      'linkedin-circled-shake',
      'twitter',
      'twitter-circled-click',
      'twitter-circled-rotation',
      'twitter-circled-scale',
      'twitter-circled-shake',
      'whatsapp-click',
      'whatsapp-rotation',
      'whatsapp-scale',
      'whatsapp-shake',
      'pinterest-click',
      'pinterest-rotation',
      'pinterest-scale',
      'pinterest-shake',
      'chat',
      'good',
      'facebook-like',
      'speech',
      'idea',
      'thumb-up',
      'facebook-like-unlike',
      'no-reminders',
      'twit-flying',
      'two-fingers',
      'bookmark',
      'facebook-like-morph',
      'gift-heart',
      'globe',
      'linkedin-bounce',
      'mug',
      'dribbble-circled-shake',
      'live-video-on',
      'vk-circled-shake',
      'instagram-3d',
      'instagram-shot',
      'itunes',
      'medium',
      'reddit',
      'viber',
      'youtube-play',
      'snapchat',
      'engagement-ring',
      'light-on',
      'share',
    ],
  },
  {
    name: 'Media',
    icons: [
      'play-button-circled-scale',
      'sound',
      'youtube',
      'expand-window',
      'download',
      'upload',
      'mute',
      'online',
      'pause',
      'speech',
      'stop',
      'volume-1',
      'volume-2',
      'video-record',
      'zoom',
      'wifi-search',
      'design',
      'document',
      'fullscreen',
      'play-load',
      'skip-backwards',
      'skip-forwards',
      'tune',
      'camera-off',
      'live-video-on',
      'no-mic',
      'no-mobile-phones',
      'no-sound',
      'no-video',
      'cassette',
      'cd',
      'cd-2',
      'cinema',
      'counter',
      'film-reel',
      'film-roll',
      'itunes',
      'play-record',
      'video-editing',
      'vox-player',
      'youtube-play',
      'missed-call',
      'movie',
      'no-comments',
      'no-connection',
    ],
  },
  {
    name: 'Weather',
    icons: [
      'cloudy-weather',
      'day-night-weather',
      'fog-weather',
      'haze-weather',
      'lightning-bolt-weather',
      'lightning-weather',
      'light-snowy-weather',
      'night-weather',
      'rain-cloud-weather',
      'rain-cloud-weather-2',
      'rainy-weather',
      'snow-storm-weather',
      'sunrise-weather',
      'sunset-weather',
      'sun-weather',
      'temperature-weather',
      'torrential-rain-weather',
      'windy-cloud-weather',
      'windy-weather',
      'stormy-weather',
      'save-changes',
    ],
  },
  {
    name: 'Ecommerce',
    icons: [
      'box',
      'coins',
      'dollar',
      'expensive',
      'piggy-bank',
      'withdrawal',
      'open-sign',
      'shipped',
      'shopping',
      'shopping-bag',
      'buy',
      'wallet',
      'gift',
      'gift-heart',
      'open-box',
      'box',
      'bank-card',
      'receipt',
      'perfume',
      'only-cash',
      'pos-terminal',
      'delivery',
      'diamond',
      'engagement-ring',
      'guarantee',
      'money',
      'order-completed',
      'paid',
      'payment-processed',
    ],
  },
  {
    name: 'Loaders',
    icons: [
      'hourglass',
      'circles-menu-1',
      'circles-menu-2',
      'circles-menu-3',
      'circles-menu-4',
      'circles-menu-5',
      'circles-menu-6',
      'circle-square-1',
      'circle-square-2',
      'circle-square-triangle',
      'alert',
      'clock',
      'iphone-spinner-1',
      'iphone-spinner-2',
      'loading-bar',
      'rhombus',
      'running-circle-1',
      'running-circle-2',
      'running-circle-3',
      'running-heart',
      'running-infinity',
      'spinner-1',
      'spinner-2',
      'spinner-3',
      'spinner-4',
      'spinner-5',
      'square-lines',
      'three-circles',
      'two-circles-1',
      'two-circles-2',
      'two-circles-3',
      'two-circles-4',
      'spinning-arrows',
      'spinning-circle-1',
      'spinning-circle-2',
      'typing',
      'walk',
      'activity',
      'book',
      'play-load',
      'fly-elephant',
      'synchronize-folder',
      'upload-to-cloud',
      'synchronize-cloud',
      'angry-cat',
      'basketball',
      'beating-hearts',
      'car',
      'come-back-later',
      'compass',
      'searching',
      'submit-progress',
    ],
  },
  {
    name: 'Emoji',
    icons: [
      'disappointed',
      'embarrassed',
      'in-love',
      'kawaii',
      'laughing',
      'neutral',
      'sleeping',
      'smile',
      'tongue-out',
      'wink',
      'yummy',
      'walk',
      'confused',
      'swiss-army-knife',
      'angel',
      'angry-cat',
      'beating-hearts',
      'birthday-cake',
      'blushing',
      'bow',
      'broken-heart',
      'calendar-heart',
      'cat-meow',
      'cool',
      'crying',
      'fire-in-my-heart',
      'ghost',
      'heart-lock',
      'heart-with-arrow',
      'kiss-panda',
      'letter-with-hearts',
      'light-on',
      'lips',
      'maneki',
      'nerd',
      'poo',
      'puzzled',
      'shocker',
      'silent',
      'vomited',
    ],
  },
  {
    name: 'Gestures',
    icons: [
      'two-fingers',
      'double-tap',
      'drag-left',
      'drag-right',
      'four-fingers',
      'hand-peace',
      'hand-scissors',
      'heart-in-hand',
      'middle-finger',
      'ok-hand',
      'one-finger',
      'tap',
      'three-fingers',
      'scroll-down-hand',
    ],
  },
  {
    name: 'Food',
    icons: [
      'tea',
      'birthday-cake',
      'chocolate-bar',
      'coffee',
      'cola',
      'energy-drink',
      'porridge',
      'salad',
    ],
  },
  {
    name: 'Sports',
    icons: [
      'basketball',
      'bench-press',
      'bow',
      'canoe',
      'car',
      'deadlift',
      'dumbbell',
      'medal-first-place',
      'medal-second-place',
      'medal-third-place',
      'prize',
      'pullups',
      'roller-skating',
      'row-boat',
      'rugby',
      'shuttercock',
      'skateboarding',
      'soccer-ball',
      'sup',
      'trophy',
      'volleyball',
    ],
  },
];

export function icon8Url(id: string) {
  return `https://maxst.icons8.com/vue-static/landings/animated-icons/icons/${id}/${id}.json`;
}

export function icon8Name(id: string) {
  if (iconNames[id]) {
    return iconNames[id];
  }
  return id
    .split('-')
    .map((token) => token[0].toUpperCase() + token.substr(1))
    .join(' ');
}
